### ISSUE TITLE
npm install后不行呀，提示以下信息

### ISSUE THREAD

**Issue by huangzhiwei001** [lanjingling0510/react-mobile-datepicker#11]
npm WARN deprecated cssnext@1.8.4: cssnext is now postcss-cssnext. cssnext is deprecated. See postcss-cssnext migration guide http://cssnext.io/postcss/

**Comment by lanjingling0510** [comment]
@huangzhiwei001  This is not related to this component, It should be your project cssnext version is too low.

**Comment by huangzhiwei001** [comment]
GET http://0.0.0.0:8080/ 503 (Service Unavailable)

**Comment by lanjingling0510** [comment]
@huangzhiwei001 我已经加了package-lock.json，你可以升级npm到5，再试试
