### ISSUE TITLE
onSelect事件中参数错误

### ISSUE THREAD

**Issue by wzsxyz** [lanjingling0510/react-mobile-datepicker#12]
onSelect事件中获取的参数是永远是初始时的时间，这导致组件完全失去意义。这bug也太夸张了吧？

**Comment by lanjingling0510** [comment]
@wzsxyz 不知道你是怎么使用的，发下你的用例

**Comment by wzsxyz** [comment]
http://test1.npm.yijifu.net/__build/demo.html

相关代码：

/**
* demo.html的入口文件
*/

var React = require('react');
var ReactDom = require('react-dom');

var RMDatePicker = require('react-mobile-datepicker');

var DatePicker = React.createClass({
    getInitialState: function(){
        return {
            isOpen: false,
            time: new Date(),
            value: ''
        }
    },
    componentDidMount: function(){
        var _this = this;
        $('body').on('click', '.datepicker-modal', function(){
            _this.setState({
                isOpen: false
            });
        })
    },
    render: function(){
        var _this = this;
        return (
            <div>
                <input
                    value={this.state.value}
                    className="js-datei" onFocus={function(e){
                    this.setState({
                        isOpen: true
                    });
                    $(e.target)[0].blur();
                }.bind(this)} />
                <RMDatePicker
                    value={this.state.time}
                    isOpen={!!this.state.isOpen}
                    onSelect={function(date){
                        console.log(date);
                        var year = ''+date.getFullYear();
                        var month = ''+(date.getMonth()+1);
                        var v = year + (month.length>1?month:'0'+month)
                        _this.setState({
                            time: date,
                            value: v
                        })
                    }}
                />
            </div>
            )
    }
});

ReactDom.render(<DatePicker
                     />, $('.js-date')[0]);

**Comment by lanjingling0510** [comment]
@wzsxyz https://codepen.io/lanjingling0510/pen/yXdoNB 关闭datepicker-modal直接在onSelect回调里控制
