### ISSUE TITLE
isPopup bug

### ISSUE THREAD

**Issue by 1120340041** [lanjingling0510/react-mobile-datepicker#13]
isPopup 属性会跟isOpen属性有冲突

**Comment by lanjingling0510** [comment]
@1120340041 如果isPopup为false，设置isOpen属性是没意义的，isOpen是用来控制Modal的显示或隐藏。

**Comment by 1120340041** [comment]
因为我是把这个datepicker放到我的modal里面的，但是我在我的modal里面想要控制这个datepicker的显示和隐藏,但是因为设置了isPopup,它就永远是显示状态，而不能关闭了，当然我可以用css样式hack一下，但是感觉一个组件提供的两个api有冲突性还是不太合理的，我这边也是提个建议

**Comment by lanjingling0510** [comment]
@1120340041  控制显隐的功能应该由你的modal提供，还不是这个组件。

**Comment by lanjingling0510** [comment]
@1120340041  modal元素隐藏，里面的子元素datepicker也会隐藏

**Comment by 1120340041** [comment]
@lanjingling0510这个我知道,因为我本来是想我的modal不隐藏,但是我还是可以控制datepicker的显示和隐藏的

**Comment by 1120340041** [comment]
@lanjingling0510我用的是antd,所以我本来希望的是我的modal跟你的modal没有冲突，你的那个datepicker可以在我modal打开的情况下，然后我在我的modal里面可以设置一个按钮，来控制它的显示和隐藏，不过其实这个也不算大问题，也暂时没影响到我的需求

**Comment by lanjingling0510** [comment]
@1120340041 好，谢谢你的建议~
