### ISSUE TITLE
安卓上不能马上滑动，设置最小时间时，时间不能选当天

### ISSUE THREAD

**Issue by xiaowang1314** [lanjingling0510/react-mobile-datepicker#14]
安卓上不能马上滑动，设置最小时间时，时间不能选当天

**Comment by lanjingling0510** [comment]
@xiaowang1314 你是怎么设置的？

**Comment by qq942159888** [comment]
有没有完整的代码，我用的时候一直报错，类型错误。无法把页面渲染啊

**Comment by cathy-zhao** [comment]
设置最大时间为当天时，当天不可选？

**Comment by zengxiaoluan** [comment]
可以这样：
`<DatePicker
                    value={new Date()}
                    isOpen={this.state.isOpenDateBox}
                    theme={'ios'}
                    min={new Date(minYear, minMonth, minDay, minHours, minMinutes)}
                    max={new Date(maxYear, maxMonth, maxDay, 23, 59, 59)}
                    dateFormat={['YY年','MM月','DD日','hh時','mm分']}
                    onSelect={this.dateSelectHandler}
                    onCancel={_=>this.setState({isOpenDateBox: false})} />`
