### ISSUE TITLE
麻烦支持一下react16

### ISSUE THREAD

**Issue by 429365799** [lanjingling0510/react-mobile-datepicker#15]
![image](https://user-images.githubusercontent.com/7577355/31375140-2ab18042-ad66-11e7-8d2e-fa4cbc7ce8f3.png)
这里就算改成react 16的写法应该也不会影响到react 15 的正常使用的吧，但react 16会报错

**Comment by lanjingling0510** [comment]
@429365799 组件已经更新了，v3.0.7已经支持react 16
