### ISSUE TITLE
Relative positioning

### ISSUE THREAD

**Issue by ingava** [lanjingling0510/react-mobile-datepicker#19]
Thanks for this nice widget. I'm building a progressive web app and finding a calendar picker that would be mobile friendly is very hard. I really like this library, however, it would be useful if we could have some control over its positioning. Currently, it has `position:absolute` and it's always placed at the bottom of the screen. That may not always suit the design. Is there a way to modify the positioning now?

**Comment by lanjingling0510** [comment]
@ingava The more direct way is, you can set isPopup to false and then implement the modal control part yourself ~
