### ISSUE TITLE
use on-page instead of as popup?

### ISSUE THREAD

**Issue by tconroy** [lanjingling0510/react-mobile-datepicker#2]
Hi.. is it possible to use this component as a widget directly on the page, without having to use it as a popup / overlay on the page?

**Comment by lanjingling0510** [comment]
@tconroy  Hey, Taking into account the mobile end is not suitable for direct display of this component to the page. In order to control the on and off date picker, I added popup. If you want to control the behavior of the popup itself, this is a worthwhile proposition.

**Comment by tconroy** [comment]
@lanjingling0510 right.. I'm actually using this for a desktop + mobile app ( I need the mobile-style drum date/time picker on desktop as well). So it is suitable for my use case.

Controlling the behavior of the popup itself would be great.

**Comment by lanjingling0510** [comment]
Thank you @tconroy , I will be independent of a component for this situation soon.

**Comment by tconroy** [comment]
@lanjingling0510 Thank you!
