### ISSUE TITLE
When scrolling 2 wheels at the same it is possible to set a date outside min/maxDate

### ISSUE THREAD

**Issue by magom001** [lanjingling0510/react-mobile-datepicker#27]
Hi!

We found an issue with the datepicker. It is possible to set a date outside the min/max boundary by scrolling two wheels at the same time. In this case the whole component becomes disabled and it is impossible to change date.

I suggest you add a check to the componentDidUpdate() life cycle:
if value > max => set value to max
if value < min => set value to min

Thank You for the feedback!

Arkady

**Comment by lanjingling0510** [comment]
@magom001 Ok ，I have already recovered the problem.

**Comment by magom001** [comment]
Sorry about the code. I have a 'prettier' plugin installed in my IDE. Didn't pay attention to the fact that it formatted the code.

So, the issue is fixed?
