### ISSUE TITLE
bundle error

### ISSUE THREAD

**Issue by geminiyellow** [lanjingling0510/react-mobile-datepicker#29]
@lanjingling0510 

thanks for your library.

use latest version, 
and when i do `react-native run-ios`
got this:
```
error: bundling failed: Error: Couldn't find preset "stage-0" relative to directory "/Users/apps/node_modules/react-mobile-datepicker"
```

**Comment by geminiyellow** [comment]
and when i install what i dont need (`stage-0`, `es2015`, i use `env`).

got this:

![image](https://user-images.githubusercontent.com/929878/41531829-ad06a0c4-732f-11e8-831e-e9f328fa50c2.png)

maybe came from here

https://github.com/lanjingling0510/react-mobile-datepicker/blob/fb2c2ef1461f06bcc3a5d6b4b821907afc22ceb6/lib/Modal.js#L45

**Comment by geminiyellow** [comment]
is it only work for web?

**Comment by lanjingling0510** [comment]
@geminiyellow Just make sure it works well on the web.Maybe rn doesn't have a noscript tag.Is there any other problem with replacing it with null?
