### ISSUE TITLE
Support Language and button customized is necessary

### ISSUE THREAD

**Issue by LingodX** [lanjingling0510/react-mobile-datepicker#3]
Support Language and button customized is necessary

**Comment by rizkiandrianto** [comment]
+1. For Temporary I will fork and update in my git LOL :joy:

**Comment by rizkiandrianto** [comment]
+1

**Comment by ziarno** [comment]
did you seriously hardcode the 2 buttons that pretty much make the entire thing unusable for other languages... I like the project btw! :)

**Comment by luspav** [comment]
+1

**Comment by lanjingling0510** [comment]
Added the `confirmText` and `cancelText` properties to customize the text of the button.

**Comment by AKclown** [comment]
thanks
