### ISSUE TITLE
Allow for Caption/Headers

### ISSUE THREAD

**Issue by dejanvasic85** [lanjingling0510/react-mobile-datepicker#31]
As a user, I want to know what I am actually selecting. Would be good to have a bar at the top indicating whether it's a day, hour or year.

See example:
![image](https://user-images.githubusercontent.com/1418428/46592246-9f739b80-cb0c-11e8-986d-36833d756cd1.png)

As opposed to:
![image](https://user-images.githubusercontent.com/1418428/46592255-ac908a80-cb0c-11e8-9ff5-9cd78db1d575.png)

**Comment by lanjingling0510** [comment]
@dejanvasic85 Thank you for your feedback.Do you have any good interface design Suggestions for it?

**Comment by dejanvasic85** [comment]
Yes my first screenshot. Just use the header row instead of one of the row values.

**Comment by lanjingling0510** [comment]
@dejanvasic85 I have added this feature in react-mobile-datepicker@4.0.0

It's used like this：

```javascript
const dateConfig = {
    'hour': {
        format: 'hh',
        caption: 'Hour',
        step: 1,
    },
    'minute': {
        format: 'mm',
        caption: 'Min',
        step: 1,
    },
    'second': {
        format: 'hh',
        caption: 'Sec',
        step: 1,
    },
}

<DatePicker
	showCaption={true}
	dateConfig={dateConfig}
/>
```
