### ISSUE TITLE
flexible冲突问题

### ISSUE THREAD

**Issue by lhhuai** [lanjingling0510/react-mobile-datepicker#32]
您好，我们的h5用到了flexible组件，在metaEl.setAttribute('name', 'viewport');  metaEl.setAttribute('content', 'initial-scale=' + scale + ', maximum-scale=' + scale + ', minimum-scale=' + scale + ', user-scalable=no');，此处会改变viewport的scale，在iPhone X手机上看到的scale是0.3333，而咋们这个时间控件是根据scale=1来做的，导致整个时间插件的缩小了1/3，这个问题怎么办？

**Comment by lanjingling0510** [comment]
@lhhuai 这个没有特别好的办法，要不就放弃viewport的缩放，其他第三方组件都会有这种问题。或者样式类的css覆盖

**Comment by lhhuai** [comment]
样式类的css覆盖，这个怎么操作呢？有没有直接可以使用的覆盖样式？方便微信沟通吗？我的微信seaphyliu

**Comment by lhhuai** [comment]
或者插件能不能加个属性，使用的时候根据缩放值自己再设置

**Comment by lanjingling0510** [comment]
@lhhuai https://github.com/amfe/lib-flexible/issues/180
