### ISSUE TITLE
datepicker can't update by F5

### ISSUE THREAD

**Issue by iamstd** [lanjingling0510/react-mobile-datepicker#4]
after importing the datepicker component, when i first render the component , a problem that document is not defined  occurs in line 134 in 'react-mobile-datepicker.js' of dist. all in one word, i hope you can give me some advise to solve this. thanks.

**Comment by lanjingling0510** [comment]
Hi @iamstd , Are you using react server rendering?

**Comment by lanjingling0510** [comment]
@iamstd, Try the  release v3.0.3.

**Comment by iamstd** [comment]
thanks , it is ok.
