### ISSUE TITLE
scrolling up will update the page

### ISSUE THREAD

**Issue by iamstd** [lanjingling0510/react-mobile-datepicker#6]
hi
  i have installed you package, ui is very nice. However, when i scroll up for the past time such as 2000-12-11. this behavior will result in updating the page and can not select the time. 

hope your response.
thanks

**Comment by lanjingling0510** [comment]
@iamstd, Please tell me your browser and os.

**Comment by lanjingling0510** [comment]
@iamstd, Try the release v3.0.4
