### ISSUE TITLE
是否计划支持time时间的选择

### ISSUE THREAD

**Issue by GuoYongfeng** [lanjingling0510/react-mobile-datepicker#8]
RT

**Comment by lanjingling0510** [comment]
@GuoYongfeng 恩，如果这种需求比较多的话，会加上选择time的功能

**Comment by GuoYongfeng** [comment]
目前正在使用该组件，但缺少时分秒的选择。

**Comment by lanjingling0510** [comment]
@GuoYongfeng 你需要选择日期的同时选择时分钟，还是只选择时分钟？

**Comment by GuoYongfeng** [comment]
@lanjingling0510 选择完整的时分秒较多，类型的场景比如做倒计时、开始时间和结束时间等。但如果一下粗鲁的场景只需要时分的话，建议有props能控制就行。前期支持完整的年月日+时分秒的选择会用的比较多。
