### ISSUE TITLE
某些情况下不能滑动

### ISSUE THREAD

**Issue by neil-i** [lanjingling0510/react-mobile-datepicker#9]
在 android4.4 下 webview 被放大或者滚动，控件就不能滑动！

**Comment by lanjingling0510** [comment]
@neil-i app封装的webview?

**Comment by neil-i** [comment]
用原生的 webview 也是同样的情况

**Comment by neil-i** [comment]
您这个工程有什么办法是我可以下载到源码编辑的么？

**Comment by lanjingling0510** [comment]
@neil-i 
`git clone https://github.com/lanjingling0510/react-mobile-datepicker.git`
`npm install`
`npm start`

**Comment by neil-i** [comment]
hi,我知道如何修改了，但是具体原因我不是很清楚
在handleStart、Move、End 方法中，修改成这样
event.changedTouches[0].pageY || event.pageY
您有时间能不能修复下这个 bug，我们工程也好尽快更新库！
thx (＾_＾)

**Comment by lanjingling0510** [comment]
@neil-i 好，我看一下，争取明天解决

**Comment by lanjingling0510** [comment]
@neil-i v3.0.5已经解决这个问题
